data = [["Salut",0],["Bonjour",0],["Bonsoire",0],["Hello",0],["coucou",0],["ça va",0],["slt",0],["cc",0],
["Quel est ton nom.",1],["qu'est-ce que tu es",1],["qui es-tu",1],["ton nom s'il te plaît",1],
["Bye",2],["A plus tard",2],["Au revoir",2],["Ravi d'avoir discuté avec toi, bye",2],["A la prochaine fois",2],["Non",2],
["Merci",3],["C'est utile",3],["Génial, merci",3],["Merci de m'avoir aidé",3],
["Comment peux-tu m'aider",4],["Comment tu fonctionne ",4],["Comment fonctionne-tu ",4],["Que peux-tu faire",4],["Quelle aide fournis-tu",4],["En quoi es-tu utile",4],["Quel soutien offre-tu ",4],["Que sais-tu ",4],["De quoi s'agit-il ",4],
["quel sont les dangers et risques dans l'entreprise ou la direction",5],["comment prévenir les dangers et risques dans l'entreprise ou la direction",5],
["oui",6],["d'accord",6],["yes",6],
["Travail  sur écran ",7],["travail  sur écran ",7],
["Service de gardiennage ",8],["service de gardiennage ",8],
["Magasin ",9],["magasin ",9],
["Entretien des locaux ",10],["entretien des locaux ",10],
["désinsectisation",11],["dératisation",11],
[" vidanges des fosses",12],
["déchets",13],["évacuation des déchets",13],
[" manutentions des objets",14],
["produits chimiques",15],
[" travail sur l'écran",16],[" écran",16],
[" risque écran",17],
["dangers écran",18],
["travail sur l'écran",19],
["travail sur écran",20],[" travail écran",20],
["terrassement",21],
["oui",22],["d'accord",22],["yes",22],
["Décapage",23],["Décapage végétale",23],
["Déblaiement, Nivellement du sol ",24],
["Remblai et compactage",25],
["EPI pour la circulation sur chantier",26],
["circulation sur chantier",27],
["circulation engins",28],
["éboulement, collision engin-engin, engin-personne",29],["engin-personne",29],["éboulement",29],["collision",29],
["chutes de déblais",30],["chutes de Gravats",30],["chutes de  déblais/Gravats",30],
["le dégagement des gaz nocifs ou toxiques, poussières",31],["gaz nocifs ou toxiques, poussières",31],["gaz nocifs",31],["gaz toxiques",31],["poussières",31],
["vibrations et nuisances sonnores",32],["nuisances sonnores",32],["troubles auditives",32],["bruit",32],
["l'électrocution, électrisation",33],["électrisation",33],["électrocution",33],
["EPI pour le travail en milieu chaud",34],["EPI en milieu chaud",34],["EPI milieu chaud",34],
["Quel EPI pour le travail en milieu froid",35],
["Quelles sont les mesures préventives pour le travail en milieu thermique",36],["Quel moyen de prévention pour le travail en milieu thermique",36],
["quel sont les dangers et risques pendant la phase de fouille",37],["comment prévenir les dangers et risques pendant la phase de fouille",37],
["Excavation",38],
["Evacuation de la terre",39],
["éboulement",40],
["collision Engin-personnes, Engin-Engin",41],["collision Engin-personnes",41], ["collision  Engin-Engin",41],
["chutes d'engin",42],
["ensevelissements",43],
["intoxications gaz nocifs, explosifs, toxiques ",44],
["chutes de déblais",45],[" chutes d'objets sur les travailleurs ",45],
["troubles musculosquelettiques",46],
["écrasement, coincement sous l'engin ",47],["coincement sous l'engin ",47], ["écrasement",47],
["fondation",48],
["feraillage ",49],
["Coffrage",50],
["Betonnage",51],
["projection des particules dans les yeux ",52],["particules dans les yeux ",52],
[" travail dans la fosse",53],
["inhalation des débrits de fer",54],["débrits de fer",54],
[" postures contraignantes",55],
["chutes de plain-pied",56],
[" projection du béton",57],
["douleurs aux articulations liés à l'utilisation du vibreur",58],[" douleurs aux articulations",58],
["troubles auditives",59],
["feraillage",60],
["Cisailler les barres et Plier les barres.",61],
["Assembler des barres",62],
[" espace de travail encombré ",63],
["particules de métal et du matériel ",64],
["coffrage",65],
["EPI travail électrique",66],
["chocs électriques, Electrisation, Electrocution",67],["électriques, Electrisation, Electrocution",67],
[" EPI coffrage",68],
["travail en hauteur",69],["chute de personne",69],
["éffondrements ou écroulements des pannaux de coffrage ",70],["écroulements des pannaux de coffrage ",70],["éffondrements des pannaux de coffrage ",70],
["utilisation du matériel ou outils ",71],
["contacts électriques",72],
[" dallage",73],
["travaux d'élevation",74],["élevation",74]]
