data = [["Salut",0],["Bonjour",0],["Bonsoire",0],["Hello",0],["coucou",0],["ça va?",0],["slt",0],["cc",0],
["Quel est ton nom?.",1],["qu'est-ce que tu es?",1],["qui es-tu?",1],["ton nom s'il te plaît?",1],
["Bye",2],["A plus tard",2],["Au revoir",2],["Ravi d'avoir discuté avec toi, bye",2],["A la prochaine fois",2],["Non",2],
["Merci",3],["C'est utile",3],["Génial, merci",3],["Merci de m'avoir aidé",3],
["Comment peux-tu m'aider?",4],["Comment tu fonctionne ?",4],["Comment fonctionne-tu ?",4],["Que peux-tu faire?",4],["Quelle aide fournis-tu?",4],["En quoi es-tu utile?",4],["Quel soutien offre-tu ?",4],["Que sais-tu ?",4],["De quoi s'agit-il ?",4],
["quel sont les dangers et risques dans l'entreprise ou la direction",5],["comment prévenir les dangers et risques dans l'entreprise ou la direction",5],
["oui",6],["d'accord",6],["yes",6],
["Travail  sur écran ",7],["travail  sur écran ",7],
["Service de gardiennage ",8],["service de gardiennage ",8],
["Magasin ",9],["magasin ",9],
["Entretien des locaux ",10],["entretien des locaux ",10],
["quels sont les moyens de prevention pour la désinsectisation ou la dératisation?",11],["quelles sont les mesures preventives pour la désinsectisation ou la dératisation?",11],
["quels sont les moyens de prevention pour le vidanges des fosses",12],["quelles sont les mesures preventives pour le vidanges des fosses?",12],
["quels sont les moyens de prevention pour l'évacuation des déchets",13],["quelles sont les mesures preventives pour l'évacuation des déchets",13],
["quels sont les moyens de prevention pour la manutentions des objets",14],["quelles sont les mesures preventives pour la manutentions des objets",14],
["comment prévenir l'intoxication par les produits chimiques?",15],["que faire en cas de présence de produits chimiques?",15],["quels sont les moyens de prevention contre l'intoxication par les produits chimiques?",15],["quelles sont les mesures preventives contre l'intoxication par les produits chimiques?",15],
["Quels sont les risques liés au travail sur l'écran",16],
["Comment prévenir?",17],["Comment les prévenirs?",17],["quels sont les moyens de prévention?",17],["quels sont les mesures préventives?",17],
["Quels sont les dangers liés au travail sur l'écran",18],
["Comment prévenir?",19],["Comment les prévenirs?",19],["quels sont les moyens de prévention?",19],["quels sont les mesures préventives?",19],
["Comment prévenir les risques liés au travail sur l'écran",20],["Comment prévenir les dangers liés au travail sur l'écran",20],
["quel sont les dangers et risques pendant la phase de terrassement",21],["comment prévenir les dangers et risques pendant la phase de terrassement",21],
["oui",22],["d'accord",22],["yes",22],
["Décapage de la terre végétale",23],
["Déblaiement, Nivellement du sol ",24],
["Remblai et compactage",25],
["Quels sont les EPI pour la circulation sur chantier?",26],
["Quelles sont les mesures préventives pour la circulation sur chantier?",27],
["Les mesures préventives pour la circulation des engins",28],
["Comment prévenir les risque d'éboulement, collision engin-engin, engin-personne",29],
["Mesures préventives contre les chutes de  déblais/Gravats",30],["comment prévenir les chutes de  déblais/Gravats?",30],
["Mesures de préventions contre le dégagement des gaz nocifs ou toxiques, poussières",31],["comment prévenir les intoxication lié au dégagement des gaz nocifs ou toxiques, poussières",31],
["Comment lutté contre les vibration et nuisance sonnore",32],["Comment prévenir les vibration musculaire, troubles auditives",32],["Comment prévenir les vibration et nuisance sonnore",32],
["Les moyens  de préventions contre l'électrocution, électrisation",33],["Prevenir les risques lié à l'électrocution, électrisation",33],
["Quel EPI pour le travail en milieu chaud?",34],
["Quel EPI pour le travail en milieu froid?",35],
["Quelles sont les mesures préventives pour le travail en milieu thermique?",36],["Quel moyen de prévention pour le travail en milieu thermique",36],
["quel sont les dangers et risques pendant la phase de fouille",37],["comment prévenir les dangers et risques pendant la phase de fouille",37],
["Excavation",38],
["Evacuation de la terre",39],
["Comment prévenir le risque d'éboulement?",40],["quel moyen de prévention contre le risque d'éboulement?",40], ["Les mesures préventives contre le risque d'éboulement?",40],
["Comment prévenir  les collision Engin-personnes, Engin-Engin?",41],["quel moyen de prévention contre la collision Engin-personnes, Engin-Engin?",41], ["Les mesures préventives contre collision Engin-personnes, Engin-Engin?",41],
["Comment prévenir  les chutes d'engin ?",42],["quel moyen de prévention contre les chutes d'engin ?",42], ["Les mesures préventives contre les chutes d'engin ?",42],
["Comment prévenir  les ensevelissements ?",43],["quel moyen de prévention contre les ensevelissements ?",43], ["Les mesures préventives contre les ensevelissements ?",43],
["Comment prévenir  les intoxications liés à la presence gaz nocifs, explosifs, toxiques ?",44],["quel moyen de prévention contre les intoxications liés à la presence gaz nocifs, explosifs, toxiques ?",44], ["Les mesures préventives contre les intoxications liés à la presence gaz nocifs, explosifs, toxiques ?",44],
["Comment prévenir  les chutes de déblais ou d'autres objets sur les travailleurs ?",45],["quel moyen de prévention contre les chutes de déblais ou d'autres objets sur les travailleurs ?",45], ["Les mesures préventives contre les chutes de déblais ou d'autres objets sur les travailleurs ?",45],
["Comment prévenir  les troubles musculosquelettiques?",46],["quel moyen de prévention contre les troubles musculosquelettiques ?",46], ["Les mesures préventives contre les troubles musculosquelettiques ?",46],
["Comment prévenir  l'écrasement, coincement sous l'engin ?",47],["quel moyen de prévention contre l'écrasement, coincement sous l'engin ?",47], ["Les mesures préventives contre l'écrasement, coincement sous l'engin ?",47]]
